# Generated by ts-datapack

tellraw @p ["Group ",{"text":"books","color":"dark_purple","hoverEvent":{"action":"show_text","value":[{"text":"frame: book\nfallback: magic","color":"yellow"}]}},":\n",["* ",{"text":"book","hoverEvent":{"action":"show_item","value":"{\"id\":\"book\",\"Count\":1,\"display\":{\"Name\":\"A Cake\",\"Lore\":[\"Made by\",\"Steve & Alex\",\"With Love <3\"]}}"}},"\n"],["* ",{"text":"enchanted_book","hoverEvent":{"action":"show_item","value":"{\"id\":\"enchanted_book\",\"Count\":1,\"display\":{\"Name\":\"A Cake\",\"Lore\":[\"Made by\",\"Steve & Alex\",\"With Love <3\"]}}"}},"\n"]]

