# Generated by ts-datapack

tellraw @p ["Group ",{"text":"gravel","color":"dark_purple","hoverEvent":{"action":"show_text","value":[{"text":"frame: gravel\nfallback: dirt","color":"yellow"}]}},":\n",["* ",{"text":"gravel","hoverEvent":{"action":"show_item","value":"{\"id\":\"gravel\",\"Count\":1,\"display\":{\"Name\":\"A Cake\",\"Lore\":[\"Made by\",\"Steve & Alex\",\"With Love <3\"]}}"}},"\n"]]

