# Generated by ts-datapack

tellraw @p ["Group ",{"text":"lapis","color":"dark_purple","hoverEvent":{"action":"show_text","value":[{"text":"frame: lapis_lazuli\nfallback: precious","color":"yellow"}]}},":\n",["* ",{"text":"lapis_block","hoverEvent":{"action":"show_item","value":"{\"id\":\"lapis_block\",\"Count\":1,\"display\":{\"Name\":\"A Cake\",\"Lore\":[\"Made by\",\"Steve & Alex\",\"With Love <3\"]}}"}},"\n"],["* ",{"text":"lapis_lazuli","hoverEvent":{"action":"show_item","value":"{\"id\":\"lapis_lazuli\",\"Count\":1,\"display\":{\"Name\":\"A Cake\",\"Lore\":[\"Made by\",\"Steve & Alex\",\"With Love <3\"]}}"}},"\n"]]

