# Generated by ts-datapack

tellraw @p ["Group ",{"text":"misc","color":"dark_purple","hoverEvent":{"action":"show_text","value":[{"text":"frame: carrot_on_a_stick","color":"yellow"}]}},":\n",["* ",{"text":"carrot_on_a_stick","hoverEvent":{"action":"show_item","value":"{\"id\":\"carrot_on_a_stick\",\"Count\":1,\"display\":{\"Name\":\"A Cake\",\"Lore\":[\"Made by\",\"Steve & Alex\",\"With Love <3\"]}}"}},"\n"]]

