# Generated by ts-datapack

tellraw @p ["Group ",{"text":"sand","color":"dark_purple","hoverEvent":{"action":"show_text","value":[{"text":"frame: sand\nfallback: misc","color":"yellow"}]}},":\n",["* ",{"text":"sand","hoverEvent":{"action":"show_item","value":"{\"id\":\"sand\",\"Count\":1,\"display\":{\"Name\":\"A Cake\",\"Lore\":[\"Made by\",\"Steve & Alex\",\"With Love <3\"]}}"}},"\n"]]

