# Generated by ts-datapack

scoreboard players add @a cpl.compass_holding 0

execute as @a[nbt={"SelectedItem":{"id":"minecraft:compass"}},scores={cpl.compass_holding=0}] at @s run function compass_player_locator:show_status

execute as @a[nbt={"SelectedItem":{"id":"minecraft:compass"}},scores={cpl.compass_holding=0}] at @s run scoreboard players set @s cpl.compass_holding 1

execute as @a[scores={cpl.compass_holding=1}] unless entity @s[nbt={"SelectedItem":{"id":"minecraft:compass"}}] run scoreboard players set @s cpl.compass_holding 0

