# Generated by ts-datapack

execute as @s if entity @e[type=minecraft:item_frame,nbt={"Item":{"id":"minecraft:chest"}},distance=0..128] at @e[type=minecraft:item_frame,nbt={"Item":{"id":"minecraft:chest"}},distance=0..128,limit=1,sort=random] run teleport @s ^ ^0.5 ^-0.5

execute as @s unless entity @e[type=minecraft:item_frame,nbt={"Item":{"id":"minecraft:chest"}},distance=0..128] run function ayers_sort:sort/tools

data merge entity @s {Motion:[0.0,0.0,0.0]}

