# Generated by ts-datapack

execute at @s if entity @a[distance=10..,limit=1,sort=nearest] facing entity @a[distance=0.1..,limit=1,sort=nearest] eyes positioned ~ ~1 ~ positioned ^ ^ ^1 run particle minecraft:dust 1.0 1.0 1.0 1.0 ~ ~ ~ 0 0 0 0 1

execute at @s if entity @a[distance=10..,limit=1,sort=nearest] run effect give @a[distance=0.1..,limit=1,sort=nearest] minecraft:glowing 1

execute at @s if entity @a[distance=10..,limit=1,sort=nearest] facing entity @a[distance=0.1..,limit=1,sort=nearest] eyes positioned ~ ~1 ~ positioned ^ ^ ^2 run particle minecraft:dust 1.0 1.0 1.0 1.0 ~ ~ ~ 0 0 0 0 1

execute at @s if entity @a[distance=10..,limit=1,sort=nearest] run effect give @a[distance=0.1..,limit=1,sort=nearest] minecraft:glowing 1

execute at @s if entity @a[distance=10..,limit=1,sort=nearest] facing entity @a[distance=0.1..,limit=1,sort=nearest] eyes positioned ~ ~1 ~ positioned ^ ^ ^3 run particle minecraft:dust 1.0 1.0 1.0 1.0 ~ ~ ~ 0 0 0 0 1

execute at @s if entity @a[distance=10..,limit=1,sort=nearest] run effect give @a[distance=0.1..,limit=1,sort=nearest] minecraft:glowing 1

