# Generated by ts-datapack

execute at @a if entity @e[type=minecraft:creeper,distance=0..10] run gamerule mobGriefing false

execute at @a unless entity @e[type=minecraft:creeper,distance=0..10] run gamerule mobGriefing true

schedule function ayers_craft:creepers 10t replace

