# Generated by ts-datapack

effect give @a[scores={AC.invincible=1}] minecraft:regeneration 60 255 true
effect give @a[scores={AC.invincible=1}] minecraft:resistance 60 255 true
schedule function ayers_craft:invincibility 30s

