# Generated by ts-datapack

say "Hello AyersCraft.ts"

team add AyersCraft
team modify AyersCraft friendlyFire false
team join AyersCraft @a

schedule function ayers_craft:invincibility 1t

schedule function ayers_craft:creepers 10t

