# Generated by ts-datapack

scoreboard players enable @a cpl.menu_compass

execute as @a[scores={cpl.menu_compass=1}] at @s run function #compass_player_locator:change

execute as @a[scores={cpl.menu_compass=2}] at @s run function compass_player_locator:follow_new_entity

execute as @a[scores={cpl.menu_compass=1..}] at @s run scoreboard players set @s cpl.menu_compass 0

