# Generated by ts-datapack

scoreboard objectives add cpl.id dummy

scoreboard objectives add cpl.follow dummy

scoreboard objectives add cpl.searching dummy

scoreboard objectives add cpl.menu_compass trigger

scoreboard objectives add cpl.compass_hold dummy

