# Generated by ts-datapack

scoreboard objectives add id dummy

scoreboard objectives add follow dummy

scoreboard objectives add searching dummy

scoreboard objectives add menu_compass trigger

scoreboard objectives add compass_holding dummy

