# Generated by ts-datapack

scoreboard players add #ac_tick sort.tick 1

execute if score #ac_tick sort.tick matches 1 run function ayers_sort:second

execute if score #ac_tick sort.tick matches 21 run function ayers_sort:second

execute if score #ac_tick sort.tick matches 41 run function ayers_sort:second

execute if score #ac_tick sort.tick matches 61 run function ayers_sort:second

execute if score #ac_tick sort.tick matches 81 run function ayers_sort:second

execute if score #ac_tick sort.tick matches 2 if score #ac_cooldown sort.cooldown matches 1 run function ayers_sort:sort/cleanup

execute if score #ac_tick sort.tick matches 22 if score #ac_cooldown sort.cooldown matches 1 run function ayers_sort:sort/cleanup

execute if score #ac_tick sort.tick matches 42 if score #ac_cooldown sort.cooldown matches 1 run function ayers_sort:sort/cleanup

execute if score #ac_tick sort.tick matches 62 if score #ac_cooldown sort.cooldown matches 1 run function ayers_sort:sort/cleanup

execute if score #ac_tick sort.tick matches 82 if score #ac_cooldown sort.cooldown matches 1 run function ayers_sort:sort/cleanup

execute if score #ac_tick sort.tick matches 100.. run scoreboard players set #ac_tick sort.tick 0

scoreboard players enable @a sort.new_book

execute as @p[scores={sort.new_book=1}] at @s run function ayers_sort:get_new_book

