# Generated by ts-datapack

effect give @s minecraft:glowing 1 0 true

execute at @a[scores={cpl.follow=1..},nbt={"SelectedItem":{"id":"minecraft:compass"}}] if score @a[scores={cpl.follow=1..},nbt={"SelectedItem":{"id":"minecraft:compass"}},sort=nearest,limit=1] cpl.follow = @s cpl.id at @a[scores={cpl.follow=1..},nbt={"SelectedItem":{"id":"minecraft:compass"}},sort=nearest,limit=1] facing entity @s eyes positioned ~ ~1 ~ positioned ^ ^ ^1 run particle minecraft:dust 1.0 1.0 1.0 1.0 ~ ~ ~ 0 0 0 0 1

execute at @a[scores={cpl.follow=1..},nbt={"SelectedItem":{"id":"minecraft:compass"}}] if score @a[scores={cpl.follow=1..},nbt={"SelectedItem":{"id":"minecraft:compass"}},sort=nearest,limit=1] cpl.follow = @s cpl.id at @a[scores={cpl.follow=1..},nbt={"SelectedItem":{"id":"minecraft:compass"}},sort=nearest,limit=1] facing entity @s eyes positioned ~ ~1 ~ positioned ^ ^ ^2 run particle minecraft:dust 1.0 1.0 1.0 1.0 ~ ~ ~ 0 0 0 0 1

execute at @a[scores={cpl.follow=1..},nbt={"SelectedItem":{"id":"minecraft:compass"}}] if score @a[scores={cpl.follow=1..},nbt={"SelectedItem":{"id":"minecraft:compass"}},sort=nearest,limit=1] cpl.follow = @s cpl.id at @a[scores={cpl.follow=1..},nbt={"SelectedItem":{"id":"minecraft:compass"}},sort=nearest,limit=1] facing entity @s eyes positioned ~ ~1 ~ positioned ^ ^ ^3 run particle minecraft:dust 1.0 1.0 1.0 1.0 ~ ~ ~ 0 0 0 0 1

