# Generated by ts-datapack

scoreboard players set @s cpl.holding 1
function compass_player_locator:show_following
tellraw @s ["",{"text":"Compass tracker: ","color":"gray"},{"text":"[change]","color":"blue","clickEvent":{"action":"run_command","value":"/trigger cpl.follow_next"}}]

execute if entity @e[distance=0.1..3,sort=nearest,limit=1] run say @e[distance=0.1..3,sort=nearest,limit=1]

execute if entity @e[distance=0.1..3,sort=nearest,limit=1] run tellraw @s ["",{"text":"Compass tracker: ","color":"gray"},{"text":"[follow]","color":"blue","clickEvent":{"action":"run_command","value":"/trigger cpl.follow_new"}},{"selector":"@e[distance=0.1..3,sort=nearest,limit=1]"}]

