# Generated by ts-datapack

execute at @e[scores={cpl.id=1..}] if score @e[scores={cpl.id=1..},limit=1,sort=nearest] cpl.id = @s cpl.follow run title @a title ["",{"text":"Following"}]

execute at @e[scores={cpl.id=1..}] if score @e[scores={cpl.id=1..},limit=1,sort=nearest] cpl.id = @s cpl.follow run title @a subtitle ["",{"selector":"@e[scores={cpl.id=1..},limit=1,sort=nearest]"}]

