# Generated by ts-datapack

scoreboard players enable @a cpl.follow_new

execute as @a[scores={cpl.follow_new=1..}] at @s run function compass_player_locator:follow_new_entity

scoreboard players enable @a cpl.follow_next

execute as @a[scores={cpl.follow_next=1..}] run scoreboard players operation @s cpl.searching = @s cpl.follow

execute as @a[scores={cpl.follow_next=1..}] at @s run function compass_player_locator:change

scoreboard players add @a cpl.id 0

execute as @a[scores={cpl.id=0}, limit = 1] run function compass_player_locator:assign_id

