# Generated by ts-datapack

execute at @e[scores={cpl.id=1..}] if score @e[scores={cpl.id=1..},limit=1,sort=nearest] cpl.id = @s cpl.follow as @e[scores={cpl.id=1..},limit=1,sort=nearest] run function compass_player_locator:show_target

