# Generated by ts-datapack

# ts-datapack

scoreboard objectives add sort.new_book trigger

scoreboard objectives add sort.tick dummy

scoreboard objectives add sort.cooldown dummy

scoreboard objectives add cpl.id dummy

scoreboard objectives add cpl.follow dummy

scoreboard objectives add cpl.searching dummy

scoreboard objectives add cpl.menu_compass trigger

scoreboard objectives add cpl.compass_holding dummy

scoreboard objectives add AC.invincible dummy

