# Generated by ts-datapack

# ts-datapack

scoreboard objectives add sort.new_book trigger

scoreboard objectives add sort.tick dummy

scoreboard objectives add sort.cooldown dummy

scoreboard objectives add AC.invincible dummy

